swagger: "2.0"
info:
  title: "MultiNet API"
  description: "REST API for interacting with MultiNet server"
  version: "0.1"

definitions:
  any_type:
    description: Can have any type

  workspace_permissions:
    description: A description of a workspace's permissions
    type: object
    required:
      - maintainers
      - owner
      - public
      - readers
      - writers
    properties:
      owner:
        description: The owner of the workspace
        type: object
      maintainers:
        description: The list of maintainers of the workspace
        type: array
        items:
          type: object
      writers:
        description: The list of writers of the workspace
        type: array
        items:
          type: object
      readers:
        description: The list of readers of the workspace
        type: array
        items:
          type: object
      public:
        description: Whether this workspace is public or not
        type: boolean
    example:
      maintainers: []
      owner:
        email: guy.fieri@flavortown.com
        family_name: Fieri
        given_name: Guy
        name: Guy Fieri
        picture: "https://flowjournal.org/wp-content/uploads/2012/09/Image-1-Guy-Fieri.png"
        sub: "123456789"
      public: true
      readers: []
      writers:
        - email: bill.murray@imdb.com
          family_name: Murray
          given_name: Bill
          name: Bill Murray
          picture: https://i.pinimg.com/originals/35/bf/be/35bfbe3173cafd59c1066fabe9bb84c5.jpg
          sub: "987654321"

  graph:
    description: A description of a graph, including its constituent tables
    type: object
    properties:
      nodeTables:
        description: The node tables associated with this graph
        type: array
        items:
          type: string
      edgeTable:
        description: The edge table associated with this graph
        type: string
    example:
      nodeTables:
        - table1
        - table2
      edgeTable:
        - edges

  node_data:
    description: A record containing data associated with a single node
    type: object
    required:
      - _key
      - _id
    properties:
      _key:
        description: An identifier for this record unique within its table
        type: string
      _id:
        description: A globally unique identifier including both the table name and the key
        type: string
    additionalProperties: true
    example:
      _key: "113"
      _id: "table_name/113"
      name: "Jean-Luc Picard"
      rank: "Captain"
      commission: "USS-1701-D"

  edge_data:
    type: object
    required:
      - _key
      - _id
      - _from
      - _to
    properties:
      _key:
        description: An identifier for this record unique within its table
        type: string
      _id:
        description: A globally unique identifier including both the table name and the key
        type: string
      _from:
        description: An id for the origin node
        type: string
      _to:
        description: An id for the target node
        type: string
    additionalProperties: true
    example:
      _key: "247"
      _id: "edge_table_name/247"
      _from: "table1/23"
      _to: "table4/21"
      bandwidth: 43.1
      color: "red"

parameters:
  workspace:
    name: workspace
    in: path
    description: Name of target workspace
    required: true
    schema:
      type: string
      example: workspace3

  aql:
    name: aql
    in: body
    description: An AQL query
    required: true
    schema:
      type: string
      example: FOR member IN members RETURN member

  table:
    name: table
    in: path
    description: Name of target table
    required: true
    schema:
      type: string
      example: table4

  graph:
    name: graph
    in: path
    description: Name of target graph
    required: true
    schema:
      type: string
      example: graph6

  node:
    name: node
    in: path
    description: Key of a node
    required: true
    schema:
      type: string
      example: key0

  upload_id:
    name: upload_id
    in: path
    description: The collection ID associated with this upload
    required: true
    schema:
      type: string
      example: u-1234abcd

  direction:
    name: direction
    description: The type of edges to retrieve
    in: query
    default: all
    enum:
      - incoming
      - outgoing
      - all
    schema:
      type: string

  table_type:
    name: type
    description: The type of table to retrieve
    in: query
    default: all
    enum:
      - node
      - edge
      - all
    schema:
      type: string

  offset:
    name: offset
    in: query
    description: Offset index into a collection
    default: 0
    minimum: 0
    schema:
      type: integer
      example: 0

  limit:
    name: limit
    in: query
    description: Limiting size for query results
    default: 30
    minimum: 0
    schema:
      type: integer
      example: 30

tags:
  - name: workspace
    description: Workspace retrieval, inspection, creation, and deletion
  - name: graph
    description: Graph retrieval, inspection, traversal, creation, and deletion
  - name: table
    description: Table retrieval, inspection, creation, and deletion
  - name: uploader
    description: Uploaders for various input data formats
  - name: uploads
    description: Endpoints for multipart upload operations
  - name: user
    description: Endpoints for user operations
